"""
Traffic Simulation Engine
=========================
Discrete-event simulation of road intersections using SimPy.

SimPy works with "processes" that run concurrently but share a
single-threaded event loop. Each intersection runs its own
signal cycle process. Vehicles are generated by a Poisson process
and compete for signal green phases.

Key concepts demonstrated:
  - Adaptive signal control (green duration driven by density)
  - Emergency vehicle pre-emption (skips current cycle)
  - Congestion propagation (upstream backup when intersection is full)
"""

import simpy
import random
import time
from typing import Dict, List, Any


SIMULATION_DURATION = 120   # seconds of simulated time per run
VEHICLE_ARRIVAL_RATE = 0.3  # vehicles per simulated second (Poisson λ)


class IntersectionSimulator:
    """Simulates one intersection with adaptive traffic signals."""

    def __init__(self, env: simpy.Environment, id: str, name: str,
                 green_duration: int = 30, red_duration: int = 30):
        self.env            = env
        self.id             = id
        self.name           = name
        self.green_duration = green_duration
        self.red_duration   = red_duration
        self.phase          = "red"
        self.vehicle_count  = 0
        self.vehicles_passed = 0
        self.emergency      = False
        self.log: List[dict] = []

        # SimPy resources and processes
        self.road_capacity  = simpy.Container(env, capacity=50, init=0)
        env.process(self._signal_cycle())

    def _signal_cycle(self):
        """Main signal control loop – runs forever during simulation."""
        while True:
            # Emergency pre-emption: hold green until clear
            if self.emergency:
                self.phase = "green"
                self._record("EMERGENCY GREEN – holding for emergency vehicle")
                yield self.env.timeout(10)
                self.emergency = False
                continue

            # Adaptive green: scale with queue size
            density = min(100, (self.road_capacity.level / 50) * 100)
            if density > 75:
                green = 60
            elif density > 40:
                green = 30
            else:
                green = 20

            self.phase = "green"
            self._record(f"GREEN ({green}s) – density={density:.0f}%")
            yield self.env.timeout(green)

            self.phase = "yellow"
            self._record("YELLOW (3s)")
            yield self.env.timeout(3)

            self.phase = "red"
            self._record(f"RED ({self.red_duration}s)")
            yield self.env.timeout(self.red_duration)

    def vehicle_arrives(self):
        """Called when a vehicle arrives at the intersection."""
        self.vehicle_count += 1
        if self.road_capacity.level < self.road_capacity.capacity:
            self.road_capacity.put(1)

    def vehicles_depart(self):
        """Vehicles depart on green."""
        depart = min(5, int(self.road_capacity.level))
        if depart > 0 and self.phase == "green":
            self.road_capacity.get(depart)
            self.vehicles_passed += depart

    def activate_emergency(self):
        self.emergency = True

    def _record(self, msg: str):
        self.log.append({
            "time": round(self.env.now, 1),
            "intersection": self.id,
            "event": msg,
        })

    def stats(self) -> dict:
        density = round((self.road_capacity.level / 50) * 100, 1)
        return {
            "id":              self.id,
            "name":            self.name,
            "phase":           self.phase,
            "vehicle_count":   self.vehicle_count,
            "vehicles_passed": self.vehicles_passed,
            "queue_size":      int(self.road_capacity.level),
            "density_pct":     density,
        }


def _vehicle_generator(env: simpy.Environment,
                        intersections: List[IntersectionSimulator],
                        arrival_rate: float):
    """Poisson process: vehicles arrive at random intersections."""
    while True:
        inter_time = random.expovariate(arrival_rate)
        yield env.timeout(inter_time)
        target = random.choice(intersections)
        target.vehicle_arrives()


def _departure_process(env: simpy.Environment,
                        intersections: List[IntersectionSimulator]):
    """Every second, let vehicles depart on green signals."""
    while True:
        yield env.timeout(1)
        for inter in intersections:
            inter.vehicles_depart()


def run_simulation(duration: int = SIMULATION_DURATION,
                   emergency_at: float = None) -> Dict[str, Any]:
    """
    Run a full traffic simulation.

    Parameters
    ----------
    duration     : simulated seconds to run
    emergency_at : simulated time to inject an emergency vehicle (or None)

    Returns
    -------
    dict with per-intersection stats and event log
    """
    env = simpy.Environment()

    intersections = [
        IntersectionSimulator(env, "I1", "EDSA & Roxas Boulevard",  green_duration=30),
        IntersectionSimulator(env, "I2", "EDSA & Ayala Avenue",     green_duration=30),
        IntersectionSimulator(env, "I3", "EDSA & Boni Avenue",      green_duration=30),
        IntersectionSimulator(env, "I4", "EDSA & Magsaysay Blvd",   green_duration=30),
        IntersectionSimulator(env, "I5", "EDSA & Quezon Avenue",    green_duration=30),
        IntersectionSimulator(env, "I6", "EDSA & Ortigas Avenue",   green_duration=30),
    ]

    env.process(_vehicle_generator(env, intersections, VEHICLE_ARRIVAL_RATE))
    env.process(_departure_process(env, intersections))

    # Optional emergency injection
    if emergency_at is not None:
        def _emergency(env, t):
            yield env.timeout(t)
            for inter in intersections[:3]:   # first 3 intersections on route
                inter.activate_emergency()
        env.process(_emergency(env, emergency_at))

    start = time.perf_counter()
    env.run(until=duration)
    elapsed = time.perf_counter() - start

    # Collect all log entries
    all_logs = []
    for inter in intersections:
        all_logs.extend(inter.log)
    all_logs.sort(key=lambda x: x["time"])

    return {
        "duration_simulated_s": duration,
        "real_time_ms":         round(elapsed * 1000, 1),
        "intersections":        [i.stats() for i in intersections],
        "total_vehicles":       sum(i.vehicle_count  for i in intersections),
        "total_passed":         sum(i.vehicles_passed for i in intersections),
        "event_log":            all_logs[-50:],   # last 50 events
    }
